# Upptime configuration file
owner: Phishcan
repo: status

sites:
  - name: Phishcan Website
    url: https://phishcan.org
    method: GET
    expectedStatusCodes:
      - 200
  - name: Phishcan API
    url: https://phishcan.org/api
    method: GET
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status
  logoUrl: https://phishcan.org/logo.jpg
  name: Phishcan Status
  introTitle: "**Phishcan Status**"
  introMessage: Welcome to the Phishcan status page. Here you can see the real-time status of our services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Phishcan/status
