# Upptime configuration file
owner: Phishcan # Your GitHub username or organization name
repo: status   # Your GitHub repository name

sites:
  - name: Phishcan Website
    url: https://phishcan.org
    method: GET
    expectedStatusCodes:
      - 200
  - name: Phishcan API
    url: https://phishcan.org/api
    method: GET
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: status.phishcan.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://phishcan.org/logo.png # Replace with your logo URL
  name: Phishcan Status
  introTitle: "**Phishcan Status**"
  introMessage: Welcome to the Phishcan status page. Here you can see the real-time status of our services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Phishcan/status

# Upptime also supports notifications, assignments, and more.
# See https://github.com/upptime/upptime for more options.
