owner: Phishcan
repo: status

sites:
  - name: Phishcan Website
    url: https://phishcan.org
    method: GET
    expectedStatusCodes:
      - 200
  - name: Phishcan API
    url: https://phishcan.org/api
    method: GET
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status
  logoUrl: https://phishcan.org/logo.jpg
  name: Phishcan Status
  introTitle: "**Phishcan Status**"
  introMessage: Welcome to the Phishcan status page. Here you can see the real-time status of our services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Phishcan/status
  head: |
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
  css: |
    body {
      background-color: #1a1b1e;
      color: #e0e0e0;
      font-family: 'Inter', sans-serif;
      margin: 0;
      padding: 0;
    }

    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 2rem;
    }

    .status {
      margin: 0.75rem 0;
      padding: 1.5rem;
      border-radius: 8px;
      background: #2c2f38;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
      transition: background-color 0.3s ease, transform 0.3s ease;
    }

    .status:hover {
      transform: scale(1.02);
    }

    .status-header {
      font-weight: 600;
      font-size: 1.25rem;
      margin-bottom: 0.5rem;
      color: #f0f1f3;
    }

    .status-date {
      color: #a0a0a0;
      font-size: 0.85rem;
    }

    .status.operational {
      border-left: 4px solid #10b981;
      background-color: #33393f;
    }

    .status.degraded {
      border-left: 4px solid #f59e0b;
      background-color: #33393f;
    }

    .status.outage {
      border-left: 4px solid #ef4444;
      background-color: #33393f;
    }

    .navbar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 1rem 0;
      background-color: #121417;
      border-bottom: 1px solid #333;
    }

    .navbar a {
      color: #e0e0e0;
      text-decoration: none;
      font-size: 1rem;
      transition: color 0.2s ease;
    }

    .navbar a:hover {
      color: #10b981;
    }

    .introTitle {
      font-size: 1.75rem;
      font-weight: 700;
      color: #f0f1f3;
    }

    .introMessage {
      font-size: 1.1rem;
      color: #a0a0a0;
    }

    header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 1.5rem 0;
      background-color: #121417;
      border-bottom: 1px solid #333;
    }

    header img {
      width: 50px;
      height: 50px;
      object-fit: contain;
      border-radius: 8px;
    }

    footer {
      text-align: center;
      color: #a0a0a0;
      font-size: 0.875rem;
      padding: 2rem 0;
      border-top: 1px solid #333;
    }

    footer a {
      color: #10b981;
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }
